/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lk.luckysoft.agro.dialogbox;

import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.luckysoft.agro.connection.MySQL;

/**
 *
 * @author KAVINDU
 */
public class stock extends javax.swing.JDialog {

    HashMap<String, String> productMap = new HashMap<>();

    /**
     * Creates new form stock
     */
    public stock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadProduct();
        loadStock();
        barcodeGenerate();
    }
    private void barcodeGenerate() {

        if (this.jTextField1 == null) {
            String jTextField1 = String.valueOf(System.currentTimeMillis());
            
        }

    }

    private void loadProduct() {
        try {
            Vector productvec = new Vector();
            productvec.add("Select Product");

            ResultSet productrs = MySQL.search("SELECT * FROM `product`");
            while (productrs.next()) {
                productvec.add(productrs.getString("name"));
//                productvec.add(productrs.getString("qty"));
//                productvec.add(productrs.getString("selling_price"));
//                productvec.add(productrs.getString("barcode"));
//                productvec.add(productrs.getString("barcode"));
                productMap.put(productrs.getString("name"), productrs.getString("id"));
            }

            jComboBox1.setModel(new DefaultComboBoxModel<>(productvec));

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private void loadStock() {
        try {
            int i = 0;

            ResultSet rs = MySQL.search("SELECT * FROM `stock` INNER JOIN `product` ON `stock`.`product_id` = `product`.`id` ");
            DefaultTableModel stockDetails = (DefaultTableModel) jTable1.getModel();
            stockDetails.setRowCount(0);

            while (rs.next()) {
                i++;
                Vector<String> stockvec = new Vector<>();
                stockvec.add(rs.getString("barcode"));
//                supplierVec.add(rs.getString("fname") + " " + rs.getString("lname"));
                stockvec.add(rs.getString("qty"));
                stockvec.add(rs.getString("selling_price"));
                stockvec.add(rs.getString("product_id"));
                stockvec.add(rs.getString("name"));
                stockDetails.addRow(stockvec);
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new lk.luckysoft.agro.component.RoundedPanel();
        roundedPanel2 = new lk.luckysoft.agro.component.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        roundedButton1 = new lk.luckysoft.agro.component.RoundedButton();
        jSeparator1 = new javax.swing.JSeparator();
        roundedButton2 = new lk.luckysoft.agro.component.RoundedButton();
        jSeparator3 = new javax.swing.JSeparator();
        roundedButton3 = new lk.luckysoft.agro.component.RoundedButton();
        roundedPanel3 = new lk.luckysoft.agro.component.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundedPanel1.setLayout(new java.awt.BorderLayout());

        roundedPanel2.setPreferredSize(new java.awt.Dimension(220, 545));

        jLabel2.setText("Barcode");

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("qty");

        jLabel4.setText("Selling Price");

        jLabel6.setText("Product");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        roundedButton1.setBackground(new java.awt.Color(0, 153, 51));
        roundedButton1.setText("Add");
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });

        roundedButton2.setText("Update");
        roundedButton2.setEnabled(false);
        roundedButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roundedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton2ActionPerformed(evt);
            }
        });

        roundedButton3.setBackground(new java.awt.Color(153, 0, 0));
        roundedButton3.setText("Delete");
        roundedButton3.setEnabled(false);
        roundedButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roundedButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jTextField1)
                    .addComponent(jFormattedTextField2)
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roundedButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(roundedButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3))
                            .addComponent(roundedButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        roundedPanel1.add(roundedPanel2, java.awt.BorderLayout.LINE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Stock | Agro Shop");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "barcode", "qty", "selling_price", "product_id", "product name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel1.add(roundedPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(roundedPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        String barcode = jTextField1.getText();
        String qty = jFormattedTextField1.getText();
        String sellPrice = jFormattedTextField2.getText();
        String selectedProduct = (String) jComboBox1.getSelectedItem();
        String product = productMap.get(String.valueOf(selectedProduct));
//        String mobile = jTextField4.getText();
//        String selectedCompany = (String) jComboBox1.getSelectedItem();
//        String company = companyMap.get(String.valueOf(selectedCompany));

        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Some thing went wrong.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter qty", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (sellPrice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter  Selling Price", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (selectedProduct.equals("Select Product")) {
            JOptionPane.showMessageDialog(this, "Please select product", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            MySQL.iud("INSERT INTO `stock`(`barcode`,`qty`,`selling_price`,`product_id`) VALUES('" + barcode + "','" + qty + "','" + sellPrice + "','" + product + "') ");
            loadStock();
//            reset();

        }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    private void roundedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton2ActionPerformed
        String barcode = jTextField1.getText();
        String qty = jFormattedTextField1.getText();
//        String sellPrice = jFormattedTextField2.getText();
        String selectedProduct = (String) jComboBox1.getSelectedItem();
        String product = productMap.get(String.valueOf(selectedProduct));

        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Some thing went wrong.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter qty", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (selectedProduct.equals("Select Product")) {
            JOptionPane.showMessageDialog(this, "Please select product", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            MySQL.iud("UPDATE `stock` SET `qty`='" + qty + "',`product_id`='" + product + "' WHERE `barcode`='" + barcode + "'");
            JOptionPane.showMessageDialog(this, "SuccessFully updated stock", "Warning", JOptionPane.INFORMATION_MESSAGE);
            loadStock();

            roundedButton1.setEnabled(true);
            roundedButton2.setEnabled(false);
            roundedButton3.setEnabled(false);
//            reset();

        }
    }//GEN-LAST:event_roundedButton2ActionPerformed

    private void roundedButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton3ActionPerformed
        String barcode = jTextField1.getText();

        MySQL.iud("DELETE * FROM `stock` WHERE `barcode`='" + barcode + "' ");
        JOptionPane.showMessageDialog(this, "Sucessfully deleted stock..", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadStock();
        roundedButton1.setEnabled(true);
        roundedButton2.setEnabled(false);
        roundedButton3.setEnabled(false);
//        reset();
    }//GEN-LAST:event_roundedButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int selectedRow = jTable1.getSelectedRow();
            String barcode = (String) jTable1.getValueAt(selectedRow, 0);
            String qty = (String) jTable1.getValueAt(selectedRow, 1);
            String sellPrice = (String) jTable1.getValueAt(selectedRow, 2);
            String product = (String) jTable1.getValueAt(selectedRow, 4);

           

            jTextField1.setText(barcode);
//            jTextField1.setEnabled(false);
            jFormattedTextField1.setText(qty);
            jFormattedTextField2.setText(sellPrice);

            jComboBox1.setSelectedItem(product);

            roundedButton1.setEnabled(false);
            roundedButton2.setEnabled(true);
            roundedButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatDarkLaf.setup();
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stock dialog = new stock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private lk.luckysoft.agro.component.RoundedButton roundedButton1;
    private lk.luckysoft.agro.component.RoundedButton roundedButton2;
    private lk.luckysoft.agro.component.RoundedButton roundedButton3;
    private lk.luckysoft.agro.component.RoundedPanel roundedPanel1;
    private lk.luckysoft.agro.component.RoundedPanel roundedPanel2;
    private lk.luckysoft.agro.component.RoundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
