/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.luckysoft.agro.gui;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lk.luckysoft.agro.connection.MySQL;
import lk.luckysoft.agro.validate.Validation;

/**
 *
 * @author KAVINDU
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }

    private void init() {

        // Application Logo
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/lk/luckysoft/agro/img/app_main_Logo.png"));
        this.setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundedTextField4 = new lk.luckysoft.agro.component.RoundedTextField();
        jLabel4 = new javax.swing.JLabel();
        roundedButton2 = new lk.luckysoft.agro.component.RoundedButton();
        roundedPasswordField1 = new lk.luckysoft.agro.component.RoundedPasswordField();
        roundedButton1 = new lk.luckysoft.agro.component.RoundedButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/luckysoft/agro/img/icons8_Eye_24px_1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/luckysoft/agro/img/signin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 45, -1, 361));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agro Shop | Sign In");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 45, 393, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 142, 61, -1));
        jPanel1.add(roundedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 369, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 255, 83, -1));

        roundedButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/luckysoft/agro/img/icons8_Eye_24px_1.png"))); // NOI18N
        roundedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(roundedButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 60, 50));
        jPanel1.add(roundedPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 370, 50));

        roundedButton1.setBackground(new java.awt.Color(0, 102, 51));
        roundedButton1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1.setText("Sign In");
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundedButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 388, 158, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton2ActionPerformed
        char echochar = roundedPasswordField1.getEchoChar();

        if (String.valueOf(echochar).equals('\u0000')) {
            roundedPasswordField1.setEchoChar('\u2022');
        } else {
            JOptionPane.showConfirmDialog(this, "Don't work ");
        }


    }//GEN-LAST:event_roundedButton2ActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed

        String email = roundedTextField4.getText();
        String password = String.valueOf(roundedPasswordField1.getPassword());

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!email.matches(Validation.EMAIL_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Please enter valid email address", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (password.matches(Validation.PASSWORD_VALIDATION.validate())) {
            JOptionPane.showMessageDialog(this, "Please enter valid password", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ResultSet rs = MySQL.search("SELECT * FROM `user` "
                        + "INNER JOIN `user_type` ON `user`.`user_type_id`= `user_type`.`id`"
                        + " WHERE `email`= '" + email + "' AND `password` = '" + password + "'");

                if (rs.next()) {
//                System.out.println(rs.getString("type"));
                    if (rs.getString("type").equals("ADMIN")) {
                        new Dashboard().setVisible(true);

                    } else if (rs.getString("type").equals("Cashier")) {
                        new CashierDashboard_1().setVisible(true);
//                        System.out.println("hi bosa error 2");
                    }
//                    System.out.println("huta keliya neda");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid login Details. Please try again!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }

        }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        FlatDarculaLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private lk.luckysoft.agro.component.RoundedButton roundedButton1;
    private lk.luckysoft.agro.component.RoundedButton roundedButton2;
    private lk.luckysoft.agro.component.RoundedPasswordField roundedPasswordField1;
    private lk.luckysoft.agro.component.RoundedTextField roundedTextField4;
    // End of variables declaration//GEN-END:variables
}
